# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  azureSubscription: 39bfb9e3-d694-4732-a732-3c98b2d48555
  appName: MilesKonferanser
  containerRegistry: <Name of the Azure container registry>
  imageRepository: <Name of image repository>



stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1(39bfb9e3-d694-4732-a732-3c98b2d48555)'
        appType: 'webAppContainer'
        WebAppName: 'MilesKonferanser'
        deployToSlotOrASE: true
        ResourceGroupName: 'KonferanseSide'
        SlotName: 'production'
        DockerNamespace: 'https://mcr.microsoft.com'
        DockerRepository: 'appsvc/staticsite:latest'
