# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  azureSubscription: 39bfb9e3-d694-4732-a732-3c98b2d48555
  containerRegistry: mainpage.azurecr.io
  imageRepository: MainPage



stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: $(imageRepository)
        containerRegistry: $(containerRegistry)
        tags: |
          $(tag)


 
    

