<script>
const participants=[
  {name:'alexander.castillo',track:'Animasjon'},
  {name:'anders.grinde',track:'Animasjon'},
  {name:'anneli.weiss',track:'Selvstudier'},
  {name:'arvid.sallaup',track:'Kubernetes'},
  {name:'birte.thornquist',track:'Animasjon'},
  {name:'bjornar.almli',track:'Selvstudier'},
  {name:'brynjar.ulriksen',track:'Kubernetes'},
  {name:'dag.erik.lovgren',track:'Selvstudier'},
  {name:'frank.wisnes',track:''},
  {name:'frode.nergard',track:''},
  {name:'havard.haug',track:'Animasjon'},
  {name:'jan.frode.brunborg',track:''},
  {name:'jan-helge.bergesen',track:'Reinforcement learning'},
  {name:'joseph.sterling.grah',track:''},
  {name:'julian.ertel',track:'Animasjon'},
  {name:'karoline.raudstein',track:'Animasjon'},
  {name:'kjartan.juvik',track:'Selvstudier'},
  {name:'krister.vindenes',track:'Typescript'},
  {name:'lars.eirik.danielsen',track:'Kubernetes'},
  {name:'lene.sorensen',track:'Selvstudier'},
  {name:'malin.jakobsen',track:'Typescript'},
  {name:'martin.h.pedersen',track:''},
  {name:'nina.borslien',track:'Selvstudier'},
  {name:'olav.loen',track:'Animasjon'},
  {name:'paal.kristian.minne',track:''},
  {name:'petter.thorgersen',track:'Animasjon'},
  {name:'richard.haugen.olsen',track:''},
  {name:'robert.waagbo',track:''},
  {name:'simon.degen',track:'Animasjon'},
  {name:'steinar.dragsnes',track:'Reinforcement learning'},
  {name:'stian.skauge',track:'Animasjon'},
  {name:'stian.fauskanger',track:''},
  {name:'teis.lindemark',track:'Kubernetes'},
  {name:'thomas.hatlebrekke',track:'Reinforcement learning'},
  {name:'thomas.fauskanger',track:'Selvstudier'},
  {name:'vegard.smedsvik',track:'Typescript'},
  {name:'vermund.vedoy',track:''},
  {name:'wenche.tollevsen',track:'Animasjon'},
  {name:'yngve.sundfjord',track:'Typescript'},
  {name:'yngve.aas',track:'Typescript'},
  {name:'oyvind.almli',track:'Reinforcement learning'},
  {name:'oyvind.johannessen',track:'Kubernetes'},
  {name:'ken.nilsen',track:'Kubernetes'},
  {name:'shangavi.logeswaran',track:''},
  {name:'knut.moldekleiv',track:'Kubernetes'},
  {name:'yngve.notsund',track:'Kubernetes'},
  {name:'borghild.vikoyr',track:''},
  {name:'clementine.isager',track:''},
  {name:'kate.henriksen',track:'Selvstudier'},
  {name:'ann.kristin.haveland',track:''},
  {name:'par.wiger',track:''}]
</script>

<h1>Fagdag 15. september 2022 (Bergen)</h1>
{#each participants.filter(item=>item.track!=='') as participant}
  <div>{participant.name.slice(0,1).toUpperCase()}{participant.name.slice(1,participant.name.indexOf('.'))}: {participant.track}</div>
{/each}
