# This workflow will build and push a Docker container to an Azure Container registry when a commit is pushed to your default branch.

name: Build and deploy a container to ACR

env:
  AZURE_WEBAPP_NAME: MilesKonferanser

on:
  push:
    branches:
      - "dev"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          ORIGIN: https://konferanser.azurewebsites.net
          CONF_API_KEY: ${{secrets.CONF_API_KEY}}
          CVPARTNER_API_KEY: ${{secrets.CVPARTNER_API_KEY}}
          CREDENTIAL_SALT: ${{secrets.CREDENTIAL_SALT}}
          SANITY_TOKEN: ${{secrets.SANITY_TOKEN}}
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          SANITY_DATASET: test
          SANITY_PROJECTID: mhv8s2ia
          CVPARTNER_BASE: https://miles.cvpartner.com

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{secrets.ACR_LOGIN_SERVER}}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ACR_TAG }}
          file: ./Dockerfile
        env:
          ORIGIN: https://konferanser.azurewebsites.net
          CONF_API_KEY: ${{secrets.CONF_API_KEY}}
          CVPARTNER_API_KEY: ${{secrets.CVPARTNER_API_KEY}}
          CREDENTIAL_SALT: ${{secrets.CREDENTIAL_SALT}}
          SANITY_TOKEN: ${{secrets.SANITY_TOKEN}}
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          SANITY_DATASET: test
          SANITY_PROJECTID: mhv8s2ia
          CVPARTNER_BASE: https://miles.cvpartner.com

 
