name: Build and push container to docker repo teilin @ DO
on:
  push:
    branches:
      - releases/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v1

    - name: Login to Digital Ocean Registry
      uses: docker/login-action@v1
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DO_REGISTRT_TOKEN }}
        password: ${{ secrets.DO_REGISTRT_TOKEN }}

    - name: Build latest
      run: docker build -t registry.digitalocean.com/teilin/milesconf:$(echo $GITHUB_SHA | head -c7) -t registry.digitalocean.com/teilin/milesconf:latest .

    - name: Docker Push
      run: docker push registry.digitalocean.com/teilin/milesconf:$(echo $GITHUB_SHA | head -c7)

    - name: Docker Push
      run: docker push registry.digitalocean.com/teilin/milesconf:latest

    - name: Set up kubectl
      uses: matootie/dokube@v1.4.0
      with:
        personalAccessToken: ${{ secrets.DO_TOKEN }}
        clusterName: k8s-devgeek
        namespace: milesconf

    - name: Apply Deployment
      run: kubectl apply -f $GITHUB_WORKSPACE/deployment.yml